### ISSUE TITLE
Personal Dimension Whitelist/Blacklist not working

### ISSUE THREAD

**Issue by Ganpan14O** [AllenSeitz/DimDungeons#54] opened 2022-12-23 07:51 UTC
For some reason when I try to modify my blacklist/whitelist all the names I add have a [ added in front of them, hence making them not function.

**Comment by Ganpan14O** [comment] 2022-12-23 07:52
Accidentally hit enter, hench the bunch of edits I'm about to make

**Comment by AllenSeitz** [comment] 2022-12-23 09:18
Thank you! I've had reports of the whitelist malfunctioning but nothing as specific as hearing that there was a '[' being added to player's names.

Which version of Forge was this? And which version of my mod? Can you think of any other mods (or libraries) that might be implementing features related to player names?

**Comment by Ganpan14O** [comment] 2022-12-28 22:24
> Thank you! I've had reports of the whitelist malfunctioning but nothing as specific as hearing that there was a '[' being added to player's names.
> 
> Which version of Forge was this? And which version of my mod? Can you think of any other mods (or libraries) that might be implementing features related to player names?

forge-40.1.84
dimdungeons-168-forge-1.18.2.jar

I'm pretty sure it's an issue with a mod causing either name tags specifically or all items to have a [ before their name when mods try to get their name, as the issue has also happened with other mods that try to get the name of a name tag. My only guess as to the culprit is Apotheosis, though if it is in reality an issue with player names I could also see Jobs+ being the cause. I may be able to send you the mod pack but it's currently in development and not public so I'd need the author's permission (which is likely easy to get) and to send it in either Discord DMs or Curseforge PMs.

**Comment by AllenSeitz** [comment] 2023-01-28 13:53
Thank you for that comment! I thought it might be another mod interfering with the name tags.

Since a month ago have you been able to figure it out? I want to make a workaround in the next version for 1.18.2.

**Comment by AllenSeitz** [comment] 2023-02-01 16:27
I've confirmed the problem is Apotheosis.

**Comment by AllenSeitz** [comment] 2023-03-07 12:18
Fixed in the latest release! Download v172 and let me know if the issue still isn't fixed.

**Closed by AllenSeitz** 2023-03-07 12:18 UTC
